name: Parse AWS SSM variable as .env format and load it to the github workflow environment variables
description: Parse AWS SSM variable as .env format and load it to the github workflow environment variables

inputs:
  ssm-path:
    description: "AWS SSM path for parameter (eg. `/ssm/parameter`)"
    required: true

runs:
  using: "node16"
  main: "src/index.js"
